In [27]:
import numpy as np
y_actual = np.random.randint(10, 100, 10)
y_pred = y_actual+np.random.randint(0, 10, 10)

In [28]:
print(y_actual, y_pred)

[64 52 88 11 25 83 82 74 83 29] [69 53 96 12 32 83 90 81 83 31]


# Regression Metrics
## Mean Absolute Error

In [29]:
error_mae = y_actual - y_pred
print(error_mae)

abs_error_mae = abs(error_mae)
print(abs_error_mae)

mae = sum(abs_error_mae)/len(y_actual)
print(mae)

[-5 -1 -8 -1 -7  0 -8 -7  0 -2]
[5 1 8 1 7 0 8 7 0 2]
3.9


In [30]:
from sklearn.metrics import mean_absolute_error
f_mae = mean_absolute_error(y_pred=y_pred, y_true=y_actual)
print(f_mae)

3.9


## Mean Squared Error

In [31]:
error_mse = y_pred - y_actual

squared_error_mse = error_mse**2
print(squared_error_mse)

mse = sum(squared_error_mse)/len(y_actual)
print(mse)

[25  1 64  1 49  0 64 49  0  4]
25.7


In [32]:
from sklearn.metrics import mean_squared_error
f_mse = mean_squared_error(y_pred=y_pred, y_true=y_actual)

print(f_mse)

25.7


## Root Mean Squared Error

In [33]:
import math
error_rmse = y_actual - y_pred

squared_error_rmse = error_rmse**2
mse_rmse = sum(squared_error_rmse)/len(y_actual)
rmse = math.sqrt(mse_rmse)
print(rmse)

5.06951674225463


In [35]:
from sklearn.metrics import root_mean_squared_error
f_rmse = root_mean_squared_error(y_pred=y_pred, y_true=y_actual)
print(f_rmse)

5.06951674225463


## Mean Absolute Percentage Error

In [37]:
error_mape = (y_actual - y_pred)/y_actual

abs_error_mape = abs(error_mape)

sum_abs_error_mape = sum(abs_error_mape)
mape = (100/len(y_actual))*sum_abs_error_mape
print(mape)

8.202950384946812


In [38]:
from sklearn.metrics import mean_absolute_percentage_error

f_mape = mean_absolute_percentage_error(y_pred=y_pred, y_true=y_actual)
print(f_mape)

0.08202950384946811


## R Squared


In [42]:
rss_error = y_actual - y_pred
rss_squared_error = rss_error**2
rss_sum_squared_error = sum(rss_squared_error)
print(rss_sum_squared_error)

y_mean = sum(y_actual)/len(y_actual)
print(y_mean)
tss_error = y_actual - y_mean
tss_squared_error = tss_error**2
tss_sum_squared_error = sum(tss_squared_error)
print(tss_sum_squared_error)

r_squared = 1 - (rss_sum_squared_error/tss_sum_squared_error)

print(r_squared)

257
59.1
7180.900000000001
0.9642106142684065


In [43]:
from sklearn.metrics import r2_score
f_r2 = r2_score(y_pred=y_pred, y_true=y_actual)
print(f_r2)

0.9642106142684065
